In [3]:
import numpy as np

#Solution to Question 1:
arr1 = np.arange(2, 50, 3)
print(arr1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [6]:
#Solution to Question 2:

#creating two lists
list1 = []
list2 = []

for x in range(5):
    list1.append(int(input('\nEnter element of list1: ')))
    

for x in range(5):
    list2.append(int(input('\nEnter element of list2: ')))

npList1 = np.array(list1)
npList2 = np.array(list2)

print('Type of npList1: ',type(npList1))
print('Type of npList2: ',type(npList2))

np_concatList = np.concatenate((npList1, npList2))

print('Concatenated List: ',np_concatList)

sortedList = np.sort(np_concatList)

print('Sorted List: ',sortedList)


Enter element of list1: 1

Enter element of list1: 3

Enter element of list1: 5

Enter element of list1: 7

Enter element of list1: 9

Enter element of list2: 2

Enter element of list2: 4

Enter element of list2: 6

Enter element of list2: 8

Enter element of list2: 10
Type of npList1:  <class 'numpy.ndarray'>
Type of npList2:  <class 'numpy.ndarray'>
Concatenated List:  [ 1  3  5  7  9  2  4  6  8 10]
Sorted List:  [ 1  2  3  4  5  6  7  8  9 10]


In [7]:
arr_2D = np.array([[2,4,6,8], [1,3,5,7]])

print('Dimensions of ndarray: ',arr_2D.ndim)

print('Size of ndarray: ',arr_2D.size)

Dimensions of ndarray:  2
Size of ndarray:  8


In [16]:
arr_1D = np.array([1,2,3,4,5,6,7,8])

print('arr_1D type: ',type(arr_1D))

#converting 1D array to 2D by expanding in row:
arr_2D = arr_1D[np.newaxis, : ]
print('Expanding row using new-axis: ',arr_2D)
print('\nShape of arr_2D: ',np.shape(arr_2D))

arr_2D = np.expand_dims(arr_1D, axis = 0)

print('\nExpanding row using expand_dims: ',arr_2D)
print('\nShape of arr_2D: ',np.shape(arr_2D))


#converting 1D array to 2D by expanding in column:
arr_2D = arr_1D[:, np.newaxis]
print('\n\nExpanding column using new-axis: ',arr_2D)
print('\nShape of arr_2D: ',np.shape(arr_2D))

arr_2D = np.expand_dims(arr_1D, axis = 1)

print('\nExpanding column using expand_dims: ',arr_2D)
print('\nShape of arr_2D: ',np.shape(arr_2D))

arr_1D type:  <class 'numpy.ndarray'>
Expanding row using new-axis:  [[1 2 3 4 5 6 7 8]]

Shape of arr_2D:  (1, 8)

Expanding row using expand_dims:  [[1 2 3 4 5 6 7 8]]

Shape of arr_2D:  (1, 8)


Expanding column using new-axis:  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

Shape of arr_2D:  (8, 1)

Expanding column using expand_dims:  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

Shape of arr_2D:  (8, 1)


In [21]:
sq_arr1 = np.square(np.array([[1,2], [3,4]]))
sq_arr2 = np.square(np.array([[5,6], [7,8]]))

v_stack = np.vstack((sq_arr1, sq_arr2))
h_stack = np.hstack((sq_arr1, sq_arr2))

print('Vertically stacking arrays: \n',v_stack)
print('\n\nHorizontally stacking arrays: \n',h_stack)

Vertically stacking arrays: 
 [[ 1  4]
 [ 9 16]
 [25 36]
 [49 64]]


Horizontally stacking arrays: 
 [[ 1  4 25 36]
 [ 9 16 49 64]]


In [7]:
arr1 = np.array([1,2,4,3,3,5,6,7,8,8,9,1,2])

unique_arr1 = np.unique(arr1)

print('Unique elements are: ',unique_arr1)
print('Count of unique items is: ',unique_arr1.size)

Unique elements are:  [1 2 3 4 5 6 7 8 9]
Count of unique items is:  9
